services:
  - type: web
    name: lmn-to-qb-invoice
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: QBO_CLIENT_ID
        sync: false
      - key: QBO_CLIENT_SECRET
        sync: false
      - key: QBO_REDIRECT_URI
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
